import { useState, useEffect, useRef } from 'react';

// ========== بيانات افتراضية ==========
const defaultBasicStore = [
  { id: 1, categoryName: 'Microphones', items: [
    { id: 101, name: 'Shure SM58', qty: 20, status: 'good' },
    { id: 102, name: 'Sennheiser e835', qty: 10, status: 'good' },
    { id: 103, name: 'AKG C414', qty: 4, status: 'faulty' },
  ]},
  { id: 2, categoryName: 'Speakers', items: [
    { id: 201, name: 'Yamaha DXR12', qty: 8, status: 'good' },
    { id: 202, name: 'QSC K12.2', qty: 6, status: 'faulty' },
  ]},
  { id: 3, categoryName: 'Stands', items: [
    { id: 301, name: 'K&M 210/9', qty: 15, status: 'good' },
  ]},
];

const defaultWarehouse = [
  { id: 1, categoryName: 'Microphones', items: [
    { id: 101, name: 'Shure SM58', qty: 10, status: 'good' },
    { id: 102, name: 'Sennheiser e835', qty: 5, status: 'faulty' },
  ]},
  { id: 2, categoryName: 'Speakers', items: [
    { id: 201, name: 'Yamaha DXR12', qty: 4, status: 'good' },
  ]},
];

const defaultTheaters = [
  { id: 1, name: 'Jeddah Theater', categories: [
    { id: 11, categoryName: 'Microphones', items: [
      { id: 1101, name: 'Shure SM58', qty: 3, status: 'faulty' },
    ]}
  ]},
  { id: 2, name: 'Riyadh Theater', categories: [
    { id: 21, categoryName: 'Speakers', items: [
      { id: 2101, name: 'QSC K12.2', qty: 2, status: 'good' },
    ]}
  ]},
];

// ========== دالة مساعدة لتصدير PDF ==========
const exportToPDF = (title, content) => {
  const printWindow = window.open('', '_blank', 'width=800,height=600');
  const html = `
    <html dir="ltr">
      <head>
        <title>${title}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 30px; color: #1a1a2e; }
          h1 { color: #d4a017; border-bottom: 3px solid #d4a017; padding-bottom: 10px; }
          h2 { color: #2c3e50; margin-top: 25px; }
          table { width: 100%; border-collapse: collapse; margin: 15px 0; }
          th { background: #d4a017; color: #fff; padding: 10px; text-align: left; }
          td { padding: 8px 10px; border-bottom: 1px solid #eee; }
          .faulty { color: #e74c3c; font-weight: bold; }
          .good { color: #27ae60; }
          .footer { margin-top: 30px; font-size: 11px; color: #888; text-align: center; }
        </style>
      </head>
      <body>
        <h1>📦 Stockeeper - ${title}</h1>
        <p>Date: ${new Date().toLocaleDateString()} | Time: ${new Date().toLocaleTimeString()}</p>
        ${content}
        <div class="footer">Generated by Stockeeper</div>
      </body>
    </html>
  `;
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  printWindow.print();
};

// ========== شاشة الترحيب ==========
function SplashScreen() {
  return (
    <div style={splashStyles.container}>
      <div style={splashStyles.iconBox}><span style={splashStyles.iconText}>S</span></div>
      <h1 style={splashStyles.title}>Stockeeper</h1>
      <p style={splashStyles.subtitle}>Asset Manager</p>
      <div style={splashStyles.loader}><div style={splashStyles.loaderFill}></div></div>
    </div>
  );
}

// ========== الشاشة الرئيسية ==========
function Dashboard({ onNavigate, faultyCount, basicData, warehouseData, theatersData }) {
  const [searchTerm, setSearchTerm] = useState('');
  const [searchResults, setSearchResults] = useState([]);
  const [showResults, setShowResults] = useState(false);

  const handleSearch = (term) => {
    setSearchTerm(term);
    if (!term.trim()) { setSearchResults([]); setShowResults(false); return; }
    const results = []; const lowerTerm = term.toLowerCase();
    basicData.forEach((cat) => { cat.items.forEach((item) => { if (item.name.toLowerCase().includes(lowerTerm)) { const existing = results.find((r) => r.name.toLowerCase() === item.name.toLowerCase()); if (!existing) results.push({ name: item.name, basicQty: item.qty, warehouseQty: 0, theaters: [] }); } }); });
    warehouseData.forEach((cat) => { cat.items.forEach((item) => { if (item.name.toLowerCase().includes(lowerTerm)) { const existing = results.find((r) => r.name.toLowerCase() === item.name.toLowerCase()); if (existing) existing.warehouseQty = item.qty; else results.push({ name: item.name, basicQty: 0, warehouseQty: item.qty, theaters: [] }); } }); });
    theatersData.forEach((theater) => { theater.categories.forEach((cat) => { cat.items.forEach((item) => { if (item.name.toLowerCase().includes(lowerTerm)) { const existing = results.find((r) => r.name.toLowerCase() === item.name.toLowerCase()); if (existing) { const t = existing.theaters.find((t) => t.name === theater.name); if (t) t.qty += item.qty; else existing.theaters.push({ name: theater.name, qty: item.qty }); } else { results.push({ name: item.name, basicQty: 0, warehouseQty: 0, theaters: [{ name: theater.name, qty: item.qty }] }); } } }); }); });
    setSearchResults(results); setShowResults(true);
  };

  const totalItems = basicData.reduce((sum, cat) => sum + cat.items.reduce((s, i) => s + i.qty, 0), 0);
  const warehouseItems = warehouseData.reduce((sum, cat) => sum + cat.items.reduce((s, i) => s + i.qty, 0), 0);

  return (
    <div style={mainStyles.body}>
      <header style={mainStyles.header}>
        <h2 style={mainStyles.logo}>📦 Stockeeper</h2>
        <div style={mainStyles.headerActions}>
          <div style={{ position: 'relative' }}>
            <div style={mainStyles.searchBox}>
              <span style={mainStyles.searchIcon}>🔍</span>
              <input type="text" placeholder="Search an item..." style={mainStyles.searchInput} value={searchTerm} onChange={(e) => handleSearch(e.target.value)} onFocus={() => searchResults.length > 0 && setShowResults(true)} onBlur={() => setTimeout(() => setShowResults(false), 200)} />
            </div>
            {showResults && searchResults.length > 0 && (
              <div style={searchDropdownStyles.container}>
                {searchResults.map((result, idx) => (
                  <div key={idx} style={searchDropdownStyles.item}>
                    <div style={searchDropdownStyles.name}>{result.name}</div>
                    <div style={searchDropdownStyles.details}>
                      {result.basicQty > 0 && <span>🏢 Total: {result.basicQty}</span>}
                      {result.warehouseQty > 0 && <span> | 🏭 WH: {result.warehouseQty}</span>}
                      {result.theaters.map((t) => (<span key={t.name}> | 🎭 {t.name}: {t.qty}</span>))}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
          <div style={mainStyles.bell}>🔔<span style={mainStyles.badge}>3</span></div>
        </div>
      </header>
      <div style={mainStyles.cardsGrid}>
        <div style={mainStyles.card} onClick={() => onNavigate('basicStore')}><div style={mainStyles.cardIcon}>🏢</div><h3 style={mainStyles.cardTitle}>Basic Store</h3><p style={mainStyles.cardNumber}>{totalItems}</p><p style={mainStyles.cardSub}>Total Items</p></div>
        <div style={mainStyles.card} onClick={() => onNavigate('warehouse')}><div style={mainStyles.cardIcon}>🏭</div><h3 style={mainStyles.cardTitle}>Warehouse</h3><p style={mainStyles.cardNumber}>{warehouseItems}</p><p style={mainStyles.cardSub}>Available Items</p></div>
        <div style={mainStyles.card} onClick={() => onNavigate('theaters')}><div style={mainStyles.cardIcon}>🎭</div><h3 style={mainStyles.cardTitle}>Theaters</h3><p style={mainStyles.cardNumber}>{theatersData.length}</p><p style={mainStyles.cardSub}>Active Theaters</p></div>
        <div style={{...mainStyles.card, borderColor: faultyCount > 0 ? '#e74c3c' : '#27ae60'}} onClick={() => onNavigate('repair')}><div style={mainStyles.cardIcon}>🔧</div><h3 style={mainStyles.cardTitle}>Needs Repair</h3><p style={{...mainStyles.cardNumber, color: faultyCount > 0 ? '#e74c3c' : '#27ae60'}}>{faultyCount}</p><p style={mainStyles.cardSub}>Faulty Items</p></div>
      </div>
    </div>
  );
}

// ========== نافذة المخازن العامة ==========
function InventoryView({ title, icon, data, setData, onBack }) {
  const [newCatName, setNewCatName] = useState('');
  const [newItemName, setNewItemName] = useState({});
  const [newItemQty, setNewItemQty] = useState({});
  const [expandedCat, setExpandedCat] = useState(null);
  const [editingItem, setEditingItem] = useState(null);
  const [editQty, setEditQty] = useState('');

  const addCategory = () => { if (!newCatName.trim()) return; setData([...data, { id: Date.now(), categoryName: newCatName, items: [] }]); setNewCatName(''); };
  const deleteCategory = (catId) => setData(data.filter((cat) => cat.id !== catId));
  const addItem = (catId) => { const name = newItemName[catId]; const qty = parseInt(newItemQty[catId]); if (!name || !qty || qty < 1) return; setData(data.map((cat) => cat.id === catId ? { ...cat, items: [...cat.items, { id: Date.now(), name, qty, status: 'good' }] } : cat)); setNewItemName({ ...newItemName, [catId]: '' }); setNewItemQty({ ...newItemQty, [catId]: '' }); };
  const deleteItem = (catId, itemId) => setData(data.map((cat) => cat.id === catId ? { ...cat, items: cat.items.filter((item) => item.id !== itemId) } : cat));
  const toggleStatus = (catId, itemId) => setData(data.map((cat) => cat.id === catId ? { ...cat, items: cat.items.map((item) => item.id === itemId ? { ...item, status: item.status === 'good' ? 'faulty' : 'good' } : item) } : cat));
  const startEditItem = (catId, itemId, currentQty) => { setEditingItem({ catId, itemId }); setEditQty(currentQty.toString()); };
  const saveEditItem = (catId, itemId) => { const newQty = parseInt(editQty); if (isNaN(newQty) || newQty < 0) return; setData(data.map((cat) => cat.id === catId ? { ...cat, items: cat.items.map((item) => item.id === itemId ? { ...item, qty: newQty } : item) } : cat)); setEditingItem(null); setEditQty(''); };

  const handleExportPDF = () => {
    let htmlContent = '';
    data.forEach((cat) => {
      htmlContent += `<h2>${cat.categoryName} (${cat.items.length} items)</h2><table><tr><th>Name</th><th>Qty</th><th>Status</th></tr>`;
      cat.items.forEach((item) => {
        htmlContent += `<tr><td>${item.name}</td><td>${item.qty}</td><td class="${item.status === 'good' ? 'good' : 'faulty'}">${item.status === 'good' ? 'Good' : 'Faulty'}</td></tr>`;
      });
      htmlContent += '</table>';
    });
    exportToPDF(title, htmlContent);
  };

  return (
    <div style={modalStyles.overlay}>
      <div style={modalStyles.container}>
        <div style={modalStyles.header}>
          <button style={modalStyles.backBtn} onClick={onBack}>← Back</button>
          <h2 style={modalStyles.title}>{icon} {title}</h2>
          <button style={modalStyles.pdfBtn} onClick={handleExportPDF}>📄 PDF</button>
        </div>
        <div style={modalStyles.addRow}><input style={modalStyles.input} placeholder="New category name..." value={newCatName} onChange={(e) => setNewCatName(e.target.value)} /><button style={modalStyles.addBtn} onClick={addCategory}>+ Add Category</button></div>
        <div style={modalStyles.list}>
          {data.map((cat) => (
            <div key={cat.id} style={modalStyles.categoryCard}>
              <div style={modalStyles.categoryHeader} onClick={() => setExpandedCat(expandedCat === cat.id ? null : cat.id)}>
                <span style={modalStyles.arrow}>{expandedCat === cat.id ? '▼' : '▶'}</span><span style={modalStyles.catName}>{cat.categoryName}</span><span style={modalStyles.itemCount}>({cat.items.length} items)</span>
                <button style={modalStyles.deleteBtn} onClick={(e) => { e.stopPropagation(); deleteCategory(cat.id); }}>🗑️</button>
              </div>
              {expandedCat === cat.id && (
                <div style={modalStyles.itemsContainer}>
                  {cat.items.map((item) => (
                    <div key={item.id} style={modalStyles.itemRow}>
                      <span style={modalStyles.itemName}>{item.name}</span>
                      {editingItem && editingItem.catId === cat.id && editingItem.itemId === item.id ? (
                        <div style={{ display: 'flex', gap: 5, flex: 1 }}><input type="number" style={{ ...modalStyles.input, width: 60, padding: '4px 8px' }} value={editQty} onChange={(e) => setEditQty(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') saveEditItem(cat.id, item.id); }} /><button style={modalStyles.addBtn} onClick={() => saveEditItem(cat.id, item.id)}>✓</button></div>
                      ) : (<span style={modalStyles.itemQty}>Qty: {item.qty}</span>)}
                      {!editingItem && (<button style={{ ...modalStyles.statusBtn, background: '#3498db', marginRight: 5 }} onClick={() => startEditItem(cat.id, item.id, item.qty)}>✎</button>)}
                      <button style={{ ...modalStyles.statusBtn, background: item.status === 'good' ? '#27ae60' : '#e74c3c' }} onClick={() => toggleStatus(cat.id, item.id)}>{item.status === 'good' ? 'Good' : 'Faulty'}</button>
                      <button style={modalStyles.deleteBtn} onClick={() => deleteItem(cat.id, item.id)}>🗑️</button>
                    </div>
                  ))}
                  <div style={modalStyles.addItemRow}>
                    <input style={{...modalStyles.input, flex: 2}} placeholder="Item name..." value={newItemName[cat.id] || ''} onChange={(e) => setNewItemName({ ...newItemName, [cat.id]: e.target.value })} />
                    <input style={{...modalStyles.input, flex: 1}} type="number" placeholder="Qty..." value={newItemQty[cat.id] || ''} onChange={(e) => setNewItemQty({ ...newItemQty, [cat.id]: e.target.value })} />
                    <button style={modalStyles.addBtn} onClick={() => addItem(cat.id)}>+ Add</button>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ========== نافذة المسارح ==========
function TheatersView({ theaters, setTheaters, warehouseData, setWarehouseData, onBack }) {
  const [selectedTheaterId, setSelectedTheaterId] = useState(null);
  const [newTheaterName, setNewTheaterName] = useState('');
  const [newCatName, setNewCatName] = useState('');
  const [newItemName, setNewItemName] = useState('');
  const [newItemQty, setNewItemQty] = useState('');
  const [newItemSource, setNewItemSource] = useState('warehouse');
  const [expandedCat, setExpandedCat] = useState(null);
  const [editingItem, setEditingItem] = useState(null);
  const [editQty, setEditQty] = useState('');
  const [editDiff, setEditDiff] = useState(0);
  const [editMode, setEditMode] = useState(null);
  const [editTarget, setEditTarget] = useState('warehouse');

  const selectedTheater = theaters.find((t) => t.id === selectedTheaterId);
  const sourceOptions = [
    { value: 'warehouse', label: '🏭 Warehouse' },
    ...theaters.filter((t) => t.id !== selectedTheaterId).map((t) => ({ value: `theater_${t.id}`, label: `🎭 ${t.name}` })),
  ];

  const addTheater = () => { if (!newTheaterName.trim()) return; setTheaters([...theaters, { id: Date.now(), name: newTheaterName, categories: [] }]); setNewTheaterName(''); };
  const deleteTheater = (id) => { setTheaters(theaters.filter((t) => t.id !== id)); if (selectedTheaterId === id) setSelectedTheaterId(null); };
  const addCategory = () => { if (!newCatName.trim()) return; setTheaters((prev) => prev.map((t) => t.id === selectedTheaterId ? { ...t, categories: [...t.categories, { id: Date.now(), categoryName: newCatName, items: [] }] } : t)); setNewCatName(''); };
  const deleteCategory = (catId) => { setTheaters((prev) => prev.map((t) => t.id === selectedTheaterId ? { ...t, categories: t.categories.filter((c) => c.id !== catId) } : t)); };
  const deductFromSource = (source, itemName, qty) => {
    if (source === 'warehouse') setWarehouseData((prev) => prev.map((cat) => ({ ...cat, items: cat.items.map((i) => i.name.toLowerCase() === itemName.toLowerCase() && i.qty >= qty ? { ...i, qty: i.qty - qty } : i) })));
    else if (source.startsWith('theater_')) { const sourceId = parseInt(source.replace('theater_', '')); setTheaters((prev) => prev.map((t) => t.id === sourceId ? { ...t, categories: t.categories.map((c) => ({ ...c, items: c.items.map((i) => i.name.toLowerCase() === itemName.toLowerCase() && i.qty >= qty ? { ...i, qty: i.qty - qty } : i) })) } : t)); }
  };
  const addToTarget = (target, itemName, qty) => {
    if (target === 'warehouse') setWarehouseData((prev) => prev.map((cat) => ({ ...cat, items: cat.items.map((i) => i.name.toLowerCase() === itemName.toLowerCase() ? { ...i, qty: i.qty + qty } : i) })));
    else if (target.startsWith('theater_')) { const targetId = parseInt(target.replace('theater_', '')); setTheaters((prev) => prev.map((t) => t.id === targetId ? { ...t, categories: t.categories.map((c) => ({ ...c, items: c.items.map((i) => i.name.toLowerCase() === itemName.toLowerCase() ? { ...i, qty: i.qty + qty } : i) })) } : t)); }
  };
  const addItemToTheater = () => { const name = newItemName.trim(); const qty = parseInt(newItemQty); if (!name || !qty || qty < 1) return; const catId = expandedCat; deductFromSource(newItemSource, name, qty); setTheaters((prev) => prev.map((t) => t.id === selectedTheaterId ? { ...t, categories: t.categories.map((c) => c.id === catId ? { ...c, items: [...c.items, { id: Date.now(), name, qty, status: 'good' }] } : c) } : t)); setNewItemName(''); setNewItemQty(''); setNewItemSource('warehouse'); };
  const deleteItem = (catId, itemId) => { const theater = theaters.find((t) => t.id === selectedTheaterId); const category = theater?.categories.find((c) => c.id === catId); const item = category?.items.find((i) => i.id === itemId); if (item) addToTarget('warehouse', item.name, item.qty); setTheaters((prev) => prev.map((t) => t.id === selectedTheaterId ? { ...t, categories: t.categories.map((c) => c.id === catId ? { ...c, items: c.items.filter((i) => i.id !== itemId) } : c) } : t)); };
  const toggleStatus = (catId, itemId) => { setTheaters((prev) => prev.map((t) => t.id === selectedTheaterId ? { ...t, categories: t.categories.map((c) => c.id === catId ? { ...c, items: c.items.map((i) => i.id === itemId ? { ...i, status: i.status === 'good' ? 'faulty' : 'good' } : i) } : c) } : t)); };
  const startEditItem = (catId, itemId, currentQty) => { setEditingItem({ catId, itemId }); setEditQty(currentQty.toString()); setEditDiff(0); setEditMode(null); setEditTarget('warehouse'); };
  const handleQtyChange = (val) => { setEditQty(val); if (!editingItem) return; const theater = theaters.find((t) => t.id === selectedTheaterId); const category = theater?.categories.find((c) => c.id === editingItem.catId); const item = category?.items.find((i) => i.id === editingItem.itemId); if (!item) return; const newQty = parseInt(val) || 0; const diff = newQty - item.qty; setEditDiff(diff); if (diff > 0) setEditMode('increase'); else if (diff < 0) setEditMode('decrease'); else setEditMode(null); };
  const saveEditItem = (catId, itemId) => { const newQty = parseInt(editQty); if (isNaN(newQty) || newQty < 0) return; const theater = theaters.find((t) => t.id === selectedTheaterId); const category = theater?.categories.find((c) => c.id === catId); const item = category?.items.find((i) => i.id === itemId); if (!item) return; const diff = newQty - item.qty; if (diff > 0) deductFromSource(editTarget, item.name, diff); else if (diff < 0) addToTarget(editTarget, item.name, Math.abs(diff)); setTheaters((prev) => prev.map((t) => t.id === selectedTheaterId ? { ...t, categories: t.categories.map((c) => c.id === catId ? { ...c, items: c.items.map((i) => i.id === itemId ? { ...i, qty: newQty } : i) } : c) } : t)); setEditingItem(null); setEditQty(''); setEditDiff(0); setEditMode(null); setEditTarget('warehouse'); };

  const handleExportPDF = (theaterName) => {
    const theater = theaters.find((t) => t.name === theaterName);
    if (!theater) return;
    let htmlContent = '';
    theater.categories.forEach((cat) => {
      htmlContent += `<h2>${cat.categoryName} (${cat.items.length} items)</h2><table><tr><th>Name</th><th>Qty</th><th>Status</th></tr>`;
      cat.items.forEach((item) => {
        htmlContent += `<tr><td>${item.name}</td><td>${item.qty}</td><td class="${item.status === 'good' ? 'good' : 'faulty'}">${item.status === 'good' ? 'Good' : 'Faulty'}</td></tr>`;
      });
      htmlContent += '</table>';
    });
    exportToPDF(theaterName, htmlContent);
  };

  if (!selectedTheater) {
    return (
      <div style={modalStyles.overlay}>
        <div style={modalStyles.container}>
          <div style={modalStyles.header}><button style={modalStyles.backBtn} onClick={onBack}>← Back</button><h2 style={modalStyles.title}>🎭 Theaters</h2><div style={{ width: 60 }}></div></div>
          <div style={modalStyles.addRow}><input style={modalStyles.input} placeholder="New theater name..." value={newTheaterName} onChange={(e) => setNewTheaterName(e.target.value)} /><button style={modalStyles.addBtn} onClick={addTheater}>+ Add Theater</button></div>
          <div style={{ display: 'flex', gap: 15, flexWrap: 'wrap', marginTop: 20 }}>
            {theaters.map((theater) => (
              <div key={theater.id} style={{ ...mainStyles.card, minWidth: 200, cursor: 'pointer' }} onClick={() => setSelectedTheaterId(theater.id)}>
                <div style={mainStyles.cardIcon}>🎭</div><h3 style={mainStyles.cardTitle}>{theater.name}</h3><p style={mainStyles.cardSub}>{theater.categories.length} categories</p>
                <button style={{...modalStyles.deleteBtn, fontSize: 12, marginTop: 10}} onClick={(e) => { e.stopPropagation(); deleteTheater(theater.id); }}>🗑️ Delete</button>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div style={modalStyles.overlay}>
      <div style={modalStyles.container}>
        <div style={modalStyles.header}>
          <button style={modalStyles.backBtn} onClick={() => setSelectedTheaterId(null)}>← Theaters</button>
          <h2 style={modalStyles.title}>🎭 {selectedTheater.name}</h2>
          <button style={modalStyles.pdfBtn} onClick={() => handleExportPDF(selectedTheater.name)}>📄 PDF</button>
        </div>
        <div style={modalStyles.addRow}><input style={modalStyles.input} placeholder="New category..." value={newCatName} onChange={(e) => setNewCatName(e.target.value)} /><button style={modalStyles.addBtn} onClick={addCategory}>+ Add Category</button></div>
        <div style={modalStyles.list}>
          {selectedTheater.categories.map((cat) => (
            <div key={cat.id} style={modalStyles.categoryCard}>
              <div style={modalStyles.categoryHeader} onClick={() => setExpandedCat(expandedCat === cat.id ? null : cat.id)}>
                <span style={modalStyles.arrow}>{expandedCat === cat.id ? '▼' : '▶'}</span><span style={modalStyles.catName}>{cat.categoryName}</span><span style={modalStyles.itemCount}>({cat.items.length} items)</span>
                <button style={modalStyles.deleteBtn} onClick={(e) => { e.stopPropagation(); deleteCategory(cat.id); }}>🗑️</button>
              </div>
              {expandedCat === cat.id && (
                <div style={modalStyles.itemsContainer}>
                  {cat.items.map((item) => (
                    <div key={item.id} style={modalStyles.itemRow}>
                      <span style={modalStyles.itemName}>{item.name}</span>
                      {editingItem && editingItem.catId === cat.id && editingItem.itemId === item.id ? (
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 5, flex: 1 }}>
                          <div style={{ display: 'flex', gap: 5, alignItems: 'center' }}><input type="number" style={{ ...modalStyles.input, width: 60, padding: '4px 8px' }} value={editQty} onChange={(e) => handleQtyChange(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') saveEditItem(cat.id, item.id); }} /><button style={modalStyles.addBtn} onClick={() => saveEditItem(cat.id, item.id)}>✓</button></div>
                          {editMode && (<div style={{ display: 'flex', alignItems: 'center', gap: 5, flexWrap: 'wrap' }}><span style={{ fontSize: 11, color: '#555' }}>{editMode === 'increase' ? `⚠️ +${editDiff} from:` : `↩️ ${Math.abs(editDiff)} to:`}</span><select style={{ ...modalStyles.input, width: 'auto', padding: '4px 8px', fontSize: 11 }} value={editTarget} onChange={(e) => setEditTarget(e.target.value)}>{sourceOptions.map((opt) => (<option key={opt.value} value={opt.value}>{opt.label}</option>))}</select></div>)}
                        </div>
                      ) : (<span style={modalStyles.itemQty}>Qty: {item.qty}</span>)}
                      {!editingItem && (<button style={{ ...modalStyles.statusBtn, background: '#3498db', marginRight: 5 }} onClick={() => startEditItem(cat.id, item.id, item.qty)}>✎</button>)}
                      <button style={{ ...modalStyles.statusBtn, background: item.status === 'good' ? '#27ae60' : '#e74c3c' }} onClick={() => toggleStatus(cat.id, item.id)}>{item.status === 'good' ? 'Good' : 'Faulty'}</button>
                      <button style={modalStyles.deleteBtn} onClick={() => deleteItem(cat.id, item.id)}>🗑️</button>
                    </div>
                  ))}
                  <div style={{...modalStyles.addItemRow, flexDirection: 'column', gap: 8}}>
                    <div style={{ display: 'flex', gap: 8 }}><input style={{...modalStyles.input, flex: 2}} placeholder="Item name..." value={newItemName} onChange={(e) => setNewItemName(e.target.value)} /><input style={{...modalStyles.input, flex: 1}} type="number" placeholder="Qty..." value={newItemQty} onChange={(e) => setNewItemQty(e.target.value)} /></div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><span style={{ fontSize: 13, color: '#555' }}>From:</span><select style={{...modalStyles.input, flex: 1}} value={newItemSource} onChange={(e) => setNewItemSource(e.target.value)}>{sourceOptions.map((opt) => (<option key={opt.value} value={opt.value}>{opt.label}</option>))}</select><button style={modalStyles.addBtn} onClick={addItemToTheater}>+ Add</button></div>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ========== نافذة Needs Repair ==========
function RepairView({ basicData, setBasicData, warehouseData, setWarehouseData, theatersData, setTheatersData, onBack }) {
  const getAllFaulty = () => {
    const all = [];
    basicData.forEach((cat) => { cat.items.forEach((item) => { if (item.status === 'faulty') all.push({ ...item, location: 'Basic Store', catId: cat.id, source: 'basic' }); }); });
    warehouseData.forEach((cat) => { cat.items.forEach((item) => { if (item.status === 'faulty') all.push({ ...item, location: 'Warehouse', catId: cat.id, source: 'warehouse' }); }); });
    theatersData.forEach((theater) => { theater.categories.forEach((cat) => { cat.items.forEach((item) => { if (item.status === 'faulty') all.push({ ...item, location: theater.name, catId: cat.id, theaterId: theater.id, source: 'theater' }); }); }); });
    return all;
  };

  const faultyItems = getAllFaulty();

  const markAsGood = (item) => {
    if (item.source === 'basic') setBasicData((prev) => prev.map((cat) => cat.id === item.catId ? { ...cat, items: cat.items.map((i) => i.id === item.id ? { ...i, status: 'good' } : i) } : cat));
    else if (item.source === 'warehouse') setWarehouseData((prev) => prev.map((cat) => cat.id === item.catId ? { ...cat, items: cat.items.map((i) => i.id === item.id ? { ...i, status: 'good' } : i) } : cat));
    else if (item.source === 'theater') setTheatersData((prev) => prev.map((t) => t.id === item.theaterId ? { ...t, categories: t.categories.map((c) => c.id === item.catId ? { ...c, items: c.items.map((i) => i.id === item.id ? { ...i, status: 'good' } : i) } : c) } : t));
  };

  const handleExportPDF = () => {
    let htmlContent = `<table><tr><th>Name</th><th>Qty</th><th>Location</th><th>Status</th></tr>`;
    faultyItems.forEach((item) => {
      htmlContent += `<tr><td>${item.name}</td><td>${item.qty}</td><td>${item.location}</td><td class="faulty">Faulty</td></tr>`;
    });
    htmlContent += '</table>';
    exportToPDF('Needs Repair', htmlContent);
  };

  return (
    <div style={modalStyles.overlay}>
      <div style={modalStyles.container}>
        <div style={modalStyles.header}>
          <button style={modalStyles.backBtn} onClick={onBack}>← Back</button>
          <h2 style={modalStyles.title}>🔧 Needs Repair</h2>
          <button style={modalStyles.pdfBtn} onClick={handleExportPDF}>📄 PDF</button>
        </div>
        {faultyItems.length === 0 ? (
          <div style={{ textAlign: 'center', padding: 60, color: '#27ae60' }}><div style={{ fontSize: 60 }}>✅</div><h3>All items are in good condition!</h3></div>
        ) : (
          <div style={modalStyles.list}>
            {faultyItems.map((item) => (
              <div key={`${item.source}-${item.id}`} style={modalStyles.categoryCard}>
                <div style={modalStyles.itemRow}>
                  <span style={{...modalStyles.itemName, flex: 2}}>{item.name}</span>
                  <span style={{...modalStyles.itemQty, flex: 1}}>Qty: {item.qty}</span>
                  <span style={{ flex: 1, fontSize: 13, color: '#888' }}>📍 {item.location}</span>
                  <button style={{ ...modalStyles.addBtn, background: '#27ae60', padding: '6px 14px', fontSize: 12 }} onClick={() => markAsGood(item)}>✔ Mark Good</button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

// ========== التطبيق الرئيسي ==========
export default function App() {
  const [loading, setLoading] = useState(true);
  const [currentView, setCurrentView] = useState(null);
  const [basicStoreData, setBasicStoreData] = useState(defaultBasicStore);
  const [warehouseData, setWarehouseData] = useState(defaultWarehouse);
  const [theatersData, setTheatersData] = useState(defaultTheaters);

  const countFaulty = () => {
    let count = 0;
    const countIn = (data) => data.forEach((cat) => cat.items.forEach((item) => { if (item.status === 'faulty') count++; }));
    countIn(basicStoreData); countIn(warehouseData); theatersData.forEach((t) => countIn(t.categories));
    return count;
  };

  useEffect(() => { const timer = setTimeout(() => setLoading(false), 3000); return () => clearTimeout(timer); }, []);

  if (loading) return <SplashScreen />;
  if (currentView === 'basicStore') return <InventoryView title="Basic Store" icon="🏢" data={basicStoreData} setData={setBasicStoreData} onBack={() => setCurrentView(null)} />;
  if (currentView === 'warehouse') return <InventoryView title="Warehouse" icon="🏭" data={warehouseData} setData={setWarehouseData} onBack={() => setCurrentView(null)} />;
  if (currentView === 'theaters') return <TheatersView theaters={theatersData} setTheaters={setTheatersData} warehouseData={warehouseData} setWarehouseData={setWarehouseData} onBack={() => setCurrentView(null)} />;
  if (currentView === 'repair') return <RepairView basicData={basicStoreData} setBasicData={setBasicStoreData} warehouseData={warehouseData} setWarehouseData={setWarehouseData} theatersData={theatersData} setTheatersData={setTheatersData} onBack={() => setCurrentView(null)} />;
  return <Dashboard onNavigate={setCurrentView} faultyCount={countFaulty()} basicData={basicStoreData} warehouseData={warehouseData} theatersData={theatersData} />;
}

// ========== Styles ==========
const splashStyles = {
  container: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100vh', background: '#f8f9fa', fontFamily: 'Tahoma, sans-serif' },
  iconBox: { width: 100, height: 100, borderRadius: 25, background: 'linear-gradient(135deg, #f0c040, #d4a017)', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 30, boxShadow: '0 0 30px rgba(212, 160, 23, 0.4)' },
  iconText: { fontSize: 55, fontWeight: 'bold', color: '#fff' },
  title: { fontSize: 50, color: '#1a1a2e', margin: 0, letterSpacing: 5 },
  subtitle: { fontSize: 18, color: '#d4a017', letterSpacing: 8, marginTop: 10 },
  loader: { width: 200, height: 4, background: '#e0e0e0', borderRadius: 10, marginTop: 40, overflow: 'hidden' },
  loaderFill: { height: '100%', width: '100%', background: 'linear-gradient(90deg, #d4a017, #f0c040)', animation: 'load 3s ease-in-out' },
};
const mainStyles = {
  body: { fontFamily: 'Tahoma, sans-serif', background: '#f4f6f9', minHeight: '100vh', padding: '0 20px 40px', color: '#2c3e50' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '20px 0', borderBottom: '1px solid #e0e0e0', marginBottom: 30, flexWrap: 'wrap', gap: 15 },
  logo: { margin: 0, fontSize: 28, color: '#1a1a2e' },
  headerActions: { display: 'flex', alignItems: 'center', gap: 15 },
  searchBox: { display: 'flex', alignItems: 'center', background: '#fff', borderRadius: 30, padding: '8px 16px', border: '1px solid #ddd' },
  searchIcon: { fontSize: 16, marginRight: 5 },
  searchInput: { border: 'none', outline: 'none', fontSize: 14, width: 180, background: 'transparent', fontFamily: 'Tahoma' },
  bell: { position: 'relative', fontSize: 22, cursor: 'pointer', background: '#fff', padding: '10px 12px', borderRadius: '50%', boxShadow: '0 2px 8px rgba(0,0,0,0.08)' },
  badge: { position: 'absolute', top: 4, right: 6, background: '#e74c3c', color: '#fff', borderRadius: '50%', width: 18, height: 18, fontSize: 11, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  cardsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 20, marginTop: 10 },
  card: { background: '#fff', borderRadius: 20, padding: '30px 20px', textAlign: 'center', boxShadow: '0 4px 20px rgba(0,0,0,0.04)', border: '2px solid #d4a017', transition: 'transform 0.2s', cursor: 'pointer' },
  cardIcon: { fontSize: 40, marginBottom: 10 },
  cardTitle: { fontSize: 18, margin: '10px 0 5px', color: '#555' },
  cardNumber: { fontSize: 36, fontWeight: 'bold', color: '#1a1a2e', margin: '5px 0' },
  cardSub: { fontSize: 13, color: '#888', margin: 0 },
};
const searchDropdownStyles = {
  container: { position: 'absolute', top: '100%', left: 0, right: 0, background: '#fff', borderRadius: 16, marginTop: 5, boxShadow: '0 10px 40px rgba(0,0,0,0.12)', zIndex: 200, overflow: 'hidden' },
  item: { padding: '12px 18px', borderBottom: '1px solid #f0f0f0', cursor: 'pointer' },
  name: { fontWeight: 'bold', fontSize: 15, color: '#1a1a2e', marginBottom: 4 },
  details: { fontSize: 12, color: '#666', display: 'flex', gap: 10, flexWrap: 'wrap' },
};
const modalStyles = {
  overlay: { position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', background: '#f4f6f9', zIndex: 100, overflowY: 'auto', fontFamily: 'Tahoma, sans-serif' },
  container: { maxWidth: 800, margin: '0 auto', padding: '20px 20px 60px' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 25 },
  backBtn: { background: '#fff', border: '2px solid #d4a017', color: '#d4a017', padding: '8px 20px', borderRadius: 30, cursor: 'pointer', fontWeight: 'bold', fontSize: 14 },
  pdfBtn: { background: '#fff', border: '2px solid #e74c3c', color: '#e74c3c', padding: '8px 16px', borderRadius: 30, cursor: 'pointer', fontWeight: 'bold', fontSize: 13 },
  title: { margin: 0, fontSize: 26, color: '#1a1a2e' },
  addRow: { display: 'flex', gap: 10, marginBottom: 20 },
  input: { flex: 1, padding: '10px 14px', borderRadius: 10, border: '1px solid #ddd', fontSize: 14, outline: 'none', fontFamily: 'Tahoma' },
  addBtn: { background: 'linear-gradient(135deg, #f0c040, #d4a017)', border: 'none', color: '#fff', padding: '10px 18px', borderRadius: 10, fontWeight: 'bold', cursor: 'pointer', fontSize: 14, whiteSpace: 'nowrap' },
  list: { display: 'flex', flexDirection: 'column', gap: 12 },
  categoryCard: { background: '#fff', borderRadius: 16, padding: '15px 20px', boxShadow: '0 2px 10px rgba(0,0,0,0.04)' },
  categoryHeader: { display: 'flex', alignItems: 'center', gap: 10, cursor: 'pointer' },
  arrow: { fontSize: 12, color: '#888' },
  catName: { fontWeight: 'bold', fontSize: 18, flex: 1, color: '#1a1a2e' },
  itemCount: { fontSize: 13, color: '#888' },
  deleteBtn: { background: 'transparent', border: 'none', cursor: 'pointer', fontSize: 16 },
  itemsContainer: { marginTop: 15, borderTop: '1px solid #eee', paddingTop: 15 },
  itemRow: { display: 'flex', alignItems: 'center', gap: 10, padding: '8px 0', borderBottom: '1px solid #f9f9f9' },
  itemName: { flex: 2, fontWeight: '500' },
  itemQty: { flex: 1, color: '#555' },
  statusBtn: { border: 'none', color: '#fff', padding: '4px 12px', borderRadius: 20, cursor: 'pointer', fontSize: 11, fontWeight: 'bold' },
  addItemRow: { display: 'flex', gap: 8, marginTop: 10 },
};

const sheet = document.createElement('style');
sheet.innerText = `@keyframes load { 0% { width: 0%; } 100% { width: 100%; } }`;
document.head.appendChild(sheet);